### ISSUE TITLE
Update version for realm-cocoa

### ISSUE THREAD

**Issue by acacuce** [RedMadRobot/DAO#25]
The current version does not allow you to install the library using Carthage binary on Xcode 11.4, and require build it on device, maybe need upgrade to version [v4.4.0](https://github.com/realm/realm-cocoa/releases/tag/v4.4.0)
<img width="565" alt="CleanShot 2020-03-27 at 23 32 23@2x" src="https://user-images.githubusercontent.com/14136866/77798438-ebf5c280-7083-11ea-9fb3-043e10d86f94.png">

**Comment by vani2** [comment]
Done. Check out `1.4.0` version.
