### ISSUE TITLE
Опечатка в комментариях к методу

### ISSUE THREAD

**Issue by Le0nX** [RedMadRobot/DAO#26]
https://github.com/RedMadRobot/DAO/blob/af6787d98e34d607f6007a7dee5119666e32fe9b/DAO/Classes/Core/Entity.swift#L39

Не совсем понятен комментарий. Такое ощущение, что либо "it" лишний, либо потерялась часть комментария...

**Comment by vani2** [comment]
Fixed in [ver.1.4.1](https://github.com/RedMadRobot/DAO/releases/tag/1.4.1)
