### ISSUE TITLE
Можно заменить на !existingEntries.isEmpty

### ISSUE THREAD

**Issue by Le0nX** [RedMadRobot/DAO#27]
https://github.com/RedMadRobot/DAO/blob/af6787d98e34d607f6007a7dee5119666e32fe9b/DAO/Classes/CoreDataDAO/DAO/CoreDataDAO.swift#L354

Даже ваш линтер ругается.

**Comment by vani2** [comment]
Fixed in [ver.1.4.1](https://github.com/RedMadRobot/DAO/releases/tag/1.4.1)
