### ISSUE TITLE
Возможна небольшая оптимизация

### ISSUE THREAD

**Issue by Le0nX** [RedMadRobot/DAO#28]
https://github.com/RedMadRobot/DAO/blob/af6787d98e34d607f6007a7dee5119666e32fe9b/DAO/Classes/RealmDAO/Translator/RealmTranslator.swift#L41

Вызов filter можно заменить на более компактный вид:
`let entry = entries.first(where: { $0.entryId == entity.entityId })`

**Comment by vani2** [comment]
Fixed in [ver.1.4.1](https://github.com/RedMadRobot/DAO/releases/tag/1.4.1)
